/*
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
---------------------------

28 => DIVISORS: 1, 2, 4, 7, 14, 28 => n_div = 6
28 = 2^2 * 7^1 = 2^a + 7^b => n_div = (a + 1)(b + 1) = (2 + 1)(1 + 1) = 3*2 = 6
*/

#include <stdio.h>
#include <math.h>
#define N 500

int main(){
    long count1 = 1, count2, n = 0, i = 1, j, temp_n;
    while(count1 < N+1){
        count1 = 1;
        count2 = 0;
        n += i;
        temp_n = n;
        j = 2;
        while(temp_n != 1){
            // Find prime divisors
            if(temp_n%j == 0){
                count2++;
                temp_n /= j;
            }
            else{
                count1 *= (count2 + 1);
                count2 = 0;
                j++;
            }
        }
        count1 *= (count2 + 1);
        i++;
    }
    printf("n = %lu\n\n", n);
    return 0;
}